name: Deploy to ECR

on: 
  workflow_dispatch:

jobs:
  
  build:
    
    name: Publish Image to ECR
    runs-on: ubuntu-latest
   
    steps:

    - name: Pull Latest
      run: docker pull ghcr.io/metrico/fluxpipe-lambda:latest
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        local-image: ghcr.io/metrico/fluxpipe-lambda:latest
        image: public.ecr.aws/w0a4c1j8/fluxpipe-lambda:latest
